### PR TITLE
create model, add fields in db, add additional fields in user table, …

### PR DESCRIPTION
**Pull request by cthao04**
…but cannot generate migration. Okay, I'm having an issue with generating migration. Any clue to as to why? Thanks!

### CODE REVIEW

**Comment by cthao04** [comment]
This is not a gem issue, is it? When I pulled the changes I ensure to bundle install all the gems.

**Comment by Muzzh** [comment]
I just closed this PR so that there's no misclicks, normally pull requests are done when everything works :)
- there are merge conflict in 2 files: i.e. factories.rb looks like this
`<<<<<<< HEAD
  factory :king do
    type      'King'
    user_id   1
    game_id   1
    x         1
    y         2
    captured  false
=======
  factory :move do
    
>>>>>>> f0f220d50f9e4c01e61c54ad4ed90956a52e50e1`
in these cases of different information, git won't choose because it can't tell which is right
you have to pick, or in this case combine to:
`  factory :king do
    type      'King'
    user_id   1
    game_id   1
    x         1
    y         2
    captured  false
  end

  factory :move do
    
  end
`
in this case I think you might have forgotten and "end" and it thought you redefined an existing factory, rather than making a new one
- also a merge conflict in app/models/game.rb

**Comment by Muzzh** [comment]
the first line when running the migration is
`/home/vagrant/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/associations.rb:1370:in `has_many': wrong number of arguments (given 4, expected 1..3)`
you had has_many :x, :y, :z, :a
I don't think you can do that, I thought we always had different lines for those, like this:
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  `has_many  :games
  has_many :chess_pieces
  has_many :wins
  has_many :losses`
the problem was not the migration, it was that error, that the server wouldn't even boot and wouldn't do nothing cause of associations syntax
after fixing this migrations worked just fine on my localhost !

**Comment by Muzzh** [comment]
Although, in thus case we will probably need some :through associations
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by cthao04** [comment]
Oops, sorry about that. Hmm, interesting because I didn't touch the factories.rb file at all? As for the has_many I thought we were able to add them into one line, I guess not. Okay, I'd fix it and ran rake db:migrate - now its giving me a new error. Something about Duplicate User table? I'm guessing you weren't able to reproduce to error.

**Pull request closed without merging**
