### PR TITLE
:wins and :losses are field in DB, no association necessary

### PR DESCRIPTION
**Pull request by Muzzh**
Creating a bug with User database since those association can't point to anything

### CODE REVIEW

**Comment by Muzzh** [comment]
oh oops, i guess this will not pass until https://github.com/MeetingTime404/MeetingTime404/pull/25 is merged...

**Comment by cthao04** [comment]
I'll make these changes in the moves_model. Are we still waiting for the #25 to merge?

**Comment by Muzzh** [comment]
The branch has been merged. You don't really have to make changes there. Just waiting on the test fix before updating this and then this can be merged.

**Comment by cthao04** [comment]
Okay. Will this change be made in a different branch?

**Pull request closed without merging**
