### PR TITLE
Listing game that are pending (only 1 player)

### PR DESCRIPTION
**Pull request by Muzzh**
This currently shows games in simple div's on index page.
I also introduced scopes for other status since we will most likely need them. I can always remove it for this PR.
If you wanna test this on local, remember that you will need to add games yourself since we don't have a button until @netdev01 's current Story.

### CODE REVIEW

**Comment by netdev01** [comment]
My code to create game is in create_game branch, waiting for the home page to finish.

**Comment by Muzzh** [comment]
Yep!
But it isn't on master is what I meant, so until merge or someone locally merge your branch and mine,  it's not :)

**Comment by Muzzh** [comment]
Or rather, on my branch your code isn't there yet haha

**Comment by netdev01** [comment]
@Muzzh  

In index.html.erb, there is a bug.

  <% @all_games.pending.each do |game| %>
    <div>
      Game #<%= game.id %>
      Current sattus: <%= game.status %>
    </div>
  <% end %>  <--- missing

In your last commit "fixed conflicts", you removed this line.  But I am encountering problem without this line.

**Comment by Muzzh** [comment]
Oh thanks!
I should have double checked !

**Comment by AliLynne** [comment]
Looks good to me. Going ahead and merging.

**Pull request merged**
