### PR TITLE
Modals

### PR DESCRIPTION
**Pull request by AliLynne**
Added login links to index. Haven't done the modal yet because I have questions about our design. But the links are functional. Tim - if you want to add your create game button, I can come back later and clean up the design & add the modals after I make sure I know what we want where.

### CODE REVIEW

**Comment by netdev01** [comment]
@AliLynne  FYI - Sign out doesn't work.  Don't know if it should be part of this code.
No route matches [GET] "/users/sign_out"
Otherwise, it works, and the code looks good.  I approve.  You can go ahead and merge it:-)

**Comment by AliLynne** [comment]
Huh, that's weird. But yeah, it won't affect anything at the moment. When you add your button I'll go through and make sure it all works.

**Comment by Muzzh** [comment]
Cool !
- What's this popper.js ? doesn't seem to be used anywhere ? could have missed it tho.
- there's a .landing class and img in master.scss that doesn't seem to be used, same for the board.jpg or maybe this is part of the pending design question ?
- sign_out is not functional on my local.
`<%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link'%>`
I think this one need a specified method:
`<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>`

**Comment by FezVrasta** [comment]
Popper.js is required by Bootstrap v4 beta. In the alpha it used Tether

**Pull request merged**
