### PR TITLE
Game model

### PR DESCRIPTION
**Pull request by AliLynne**
Creates games controller and game model. Created the new, create, and show actions. Added minimal logic for new and test for new. Installed simple_form and put minimal form on games#new.

### CODE REVIEW

**Comment by Muzzh** [comment]
Should you put the board in the game#show?
Then, a question. Should class Game has_many :chess_pieces
And adjust class ChessPiece belongs_to :game

**Comment by AliLynne** [comment]
Since the functionality for the game#show page isn't finished, I left the board on the pages index so people could see it more easily. It's a very quick change to make when the show functionality is there. I also didn't do anything but create the game model since Choua and Teresa are handling the models. I was just supposed to do the controller setup.

**Comment by Muzzh** [comment]
Well I will need the index page to display the opened game in one of my story. I guess I can do it then.

**Comment by Muzzh** [comment]
And I think the relationships to other models should be addressed right away when we create them, as was done in the FH projects

**Comment by AliLynne** [comment]
@Muzzh You can just list the games above the game board, there's no need to wait until the code is moved. As for the model relationships I want to make sure I'm not stepping on toes here. 
@cthao04 & @tbarin are setting up the models and since this is a learning project I want to give them time to work on their tasks before doing it for them. Amie & Teresa, if you'd like me to add the relationships, let me know. Otherwise, feel free to merge this code so you already have the game model.

**Comment by Muzzh** [comment]
Ok.
Any reason why there isn't an update action ?
otherwise, i guess we should move and merge

**Comment by AliLynne** [comment]
New, create and show were the only actions listed on my checklist.

**Comment by Muzzh** [comment]
Oh i see, my bad

**Pull request merged**
