### PR TITLE
Valid move

### PR DESCRIPTION
**Pull request by netdev01**
I have added valid_move? for all pieces and also their rspec testing.  It should merge without problem to master except for the conflict with schema.rb version number, because I have a DB migration file.  I hope someone know how to handle this.

### CODE REVIEW

**Comment by netdev01** [comment]
@Muzzh 

in chess_pieces_controller.rb
- added color to the param

in rails_helper, it "should create dummy King" 
- The code from fro your code, I think
- We can keep the master code.

**Comment by netdev01** [comment]
@Muzzh 

How can we resolve the schema.rb version conflict?  Do I keep the version from master or from my branch?

**Comment by Muzzh** [comment]
@netdev01 
if you browse to here : https://github.com/MeetingTime404/MeetingTime404/pull/29/files
you can reply to individual comments I made

**Comment by Muzzh** [comment]
@netdev01 
As far as the schema.rb I'm not sure. I'm a bit confused by this.
Did you create your own moves model before the one from https://github.com/MeetingTime404/MeetingTime404/tree/moves_model
was introduced to master ?

**Comment by Muzzh** [comment]
Took a look at the schema.rb file:
```
<<<<<<< valid_move
ActiveRecord::Schema.define(version: 20170921113349) do
=======
ActiveRecord::Schema.define(version: 20170918005640) do
>>>>>>> master
```
and 
```
<<<<<<< valid_move
    t.string   "color"
=======
>>>>>>> master
```
when you merged master into your branch, didn't the CLI tell you there were conflicts ?
you normally have to resolve those, then commit and merge will complete then.
I'm quite confused as to how it completed without the conflicts being resolved.

**Pull request closed without merging**
