### PR TITLE
Devise

### PR DESCRIPTION
**Pull request by tbarin**
Installed Devise Gem

### CODE REVIEW

**Comment by AliLynne** [comment]
In config/environments/development.rb should it be port 3000 or port 3030?

Everything looks good.

**Comment by netdev01** [comment]
Looks good. What is the process to merge it?

**Comment by Muzzh** [comment]
2 cents on merging, feel free to add/remove
Procedure for merging :
- Make sure all 'issues' that arose from messages in the pull request(PR) are resolved.
- Verify that the PR passed the tests on circleCI. 
- Merge PR and leave a message.
- If possible, verify in production(heroku). I think no other merge should be done until each new merge is verified on heroku.

**Comment by tbarin** [comment]
Yes, you're right it should be port 3030. I was following git docs, not firehose. Will fix.

**Comment by AliLynne** [comment]
Oh, what about tests?

**Comment by tbarin** [comment]
I made a few changes in the most recent commit:
-changed port from 3000 to 3030
-added Heroku URL in config/environments/production.rb
-adjusted app/views/layouts/application.html.erb so that notices and alerts only appear when present
Will we eventually be using Bootstrap for styling? If so I can add Bootstrap tags as well.
-ran command to configure devise views

**Comment by Muzzh** [comment]
I was wondering about tests as well. But in TDD we assumed that devise owners did their testing right. So idk maybe this could include the factory for FG user?

**Comment by tbarin** [comment]
Right, I didn't create tests for the devise gem because I thought we assume that the person who created the gem wrote tests for its functionality?

**Comment by tbarin** [comment]
I just removed the pending test in spec/models/user_spec.rb

**Comment by tbarin** [comment]
Any ideas on the conflicts that arose on this pull request? It seems this pull request and Ali's most recent pull request are creating conflicts on schema.rb...but I don't get what's causing the problem.

**Comment by Muzzh** [comment]
Your files are not up to date with master.
You don't have the game controller etc etc
You probably need to pull from git on master then
Checkout your branch and merge them to update your branch with the code already living up on github

**Comment by Muzzh** [comment]
Look at this
https://stackoverflow.com/questions/3876977/update-git-branches-from-master
Only difference is that you need to pull the master branch from github first
I think this should be done before and PR

**Comment by Muzzh** [comment]
Other issues I see after looking at the Trello story:
- Allow a user to login by entering a username password
this is not the case currently, I don't know if we do what it ultimately, but I have done it for most of my projects at FH. information can be found here:
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
- Allow a user to signup/logout
granted it it possible to do those thing with going to the urls, it doesn't seem very practical :)
My interpretation was that this was part of this story, although we could also add a new story that does that?

**Comment by tbarin** [comment]
I am working on finding a way to fix the conflicts. My files were up to date as of yesterday when I made the pull request but because Ali and I both worked on files that affected schema.rb, and both had open pull requests, the conflicts arose after Ali's latest commits were merged. I tried rolling back my migrations and pulling from the master branch again, running the migrations again, but that didn't seem to resolve the conflicts. Trying to find a way to resolve the conflicts but will redo on a new branch if that's the only way to get it to work.

**Comment by Muzzh** [comment]
Since yesterday, Ali's game_model branch has been merged to github master
you need to update your local master, then merge it on your branch so that your branch includes the masters changes, then push the branch.
remigrating will not help because you don't have the game_model migrations on your local branch

You have two options:

The first is a merge, but this creates an extra commit for the merge.

Checkout each branch:
git checkout master
git pull origin master
git checkout devise
Then merge:

git merge origin/master
Then push:

git push origin devise



Alternatively, you can do a rebase:

git fetch
git rebase origin/master

**Comment by tbarin** [comment]
As far as other issues on Trello story:
The user can login by entering a username and password and is able to sign up and log out. I know we are doing this project with the TDD approach but I thought it wasn't necessary to write tests for the devise gem. I did double check to make sure everything worked and that a user can login, log out, and sign up by going to the URL. While this isn't following TDD practices, the only other option would be to write tests for the devise gem.
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address allows users to sign in with either an email address or a username. Do we want to add this feature? It wasn't my understanding that this was the requirement for the task on the Trello card but we can add it.

**Comment by AliLynne** [comment]
I was sort of functioning on the idea that username/email were basically
synonymous here. At least at this point. I've written tests for devise
users in another project I did. Would be happy to help with that if we want
to use them. They're pretty simple.

**Comment by Muzzh** [comment]
- username
eitherway is fine, I just noticed that Abe had mentioned username, which we don't have, I personally prefer that, as having bob@gmail.com vs ilikepotatoesinasweetsauce@ilikepotatoes.com as players is odd and shares information that some might not want to share. but it can always be added later
- login
I assumed that this included the wireframe description, since it is not anywhere else, again, I could be wrong and as I said could be put in a different story

**Comment by tbarin** [comment]
- login: I added a card to Trello yesterday to make note that we haven't built out the interface for user signup, login, and logout. I'm fine with working on those.
- conflicts: Thanks...had to rollback, merge, add db/schema.rb, run migration again.

**Comment by Muzzh** [comment]
glad it worked! :)

**Comment by Muzzh** [comment]
Should we move and merge this ?

**Pull request merged**
